import type { Metadata } from "next";
import { Raleway, Noto_Sans } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"]
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${notoSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
